- hosts:        all
  gather_facts: False
  tasks:
    
    - name: Actualizar paquete
      apt:
        update_cache: yes

    - name: Instalar curl
      apt:
        name: curl
    
    - name: Curl a google
      shell: curl google.es